### ISSUE TITLE
Pipewire support

### ISSUE THREAD

**Issue by M4G13** [buzz/volctl#38]
I've switched to [PipeWire](https://pipewire.org/) as my audio server, and it's been working perfectly except for that volctl doesn't show applications, only devices. PipeWire is meant to be a drop-in pulseaudio replacement, and should work with no modification, so this is strange.
I've had a look at the python code but the issue seems to be in the C wrapper which I don't even know where to start with.
This could be a PipeWire issue and if you don't want to support it I would completely understand, but if someone with knowledge about the C wrapper could take a look it would be appreciated.

Thanks for this application, there's nothing else that's even close.

**Comment by buzz** [comment]
PipeWire support is definitely desirable.

The C wrapper is auto-generated. Editing it directly should probably be avoided. The code has been taken from [this repo](https://github.com/Valodim/python-pulseaudio/blob/master/pulseaudio/lib_pulseaudio.py). It's documented in the [header of the file](https://github.com/buzz/volctl/blob/master/volctl/lib/pulseaudio.py#L3) how to generate these bindings from scratch.

It might be worth trying to regenerate the bindings from a current version of `libpulseaudio`.

Instead of fixing the ctypes bindings, there's also another related issue which might just solve your issue with PipeWire: #17

**Comment by M4G13** [comment]
Wow thank you so much for this!
