### ISSUE TITLE
When volume is over 100%, make the icons and symbols red, or something like that

### ISSUE THREAD

**Issue by tusqasi** [buzz/volctl#45]
This will be a good addition

**Comment by buzz** [comment]
Could you elaborate on what you mean exactly?

**Comment by tusqasi** [comment]
Volume if is over 100%, that is higher than normal.
So make the elements red to let the user know it.

**Comment by buzz** [comment]
Thanks for your input.

Concerning your proposal, I don't remember coloring the icons red being a common way of indicating >100% volume to users. I'd rather stick to user interface patterns that are common and recognizable. Otherwise, the behavior might confuse users. Also, I like the program to keep as simple as possible and don't really see the benefit in introducing this.

BTW: The tooltip does show the exact volume percentage.

**Comment by tusqasi** [comment]
> I don't remember coloring the icons red being a common way of indicating >100% 

I don't either, but i will help when someone opens a laptop from hibernating, and volume is 110%. 

>I'd rather stick to user interface patterns that are common and recognizable. Otherwise, the behavior might confuse users.

yeah it might, those who don't know
