### ISSUE TITLE
Unfunctional scale bar

### ISSUE THREAD

**Issue by FreaxMATE** [buzz/volctl#51]
There are two HD-Audio Generic scales with the left one doing nothing (no volume status level, no effect on changing the volume). Any idea how to fix this. Besides this really good job, it really locks nice and I would love to replace the stock MATE status icon with this one :)

![volctl](https://user-images.githubusercontent.com/49864414/127295931-0f352dbd-f1e4-41f7-9ce5-e2409c7a2752.gif)

**Comment by FreaxMATE** [comment]
> I looked to the code and your output pactl list.
> 
> I see in the slider_win.py that pulse api is used, and the sink list is taken. In addition, alsa.card_name is taken as label. So, if you look to your cmd output.
> 
> There are two Sink components: Sink #49, Sink #50.
> 
> Both have card names: HD-Audio Generic, but the devices are different, check sink name: alsa_output.pci-0000_04_00.1.hdmi-stereo-extra1 and alsa_output.pci-0000_04_00.6.analog-stereo.
> 
> First is for HDMI monitor, I expect that it is not plugged (but it is available), so no sound change according to your post.
> Second is analog-stereo which goes to the repros front-left, front-right.
> 
> So, according to this. It seems that this is a state that it works. Check the list after with bug, if the sinks will be different or missing, card_name missing or what will be broken.
> 
> If something will be broken, it is issue for pipewire-pulse, which doesn't provide correct implementation api for older PulseAudio.

Everything is correct. Thank you @raven2cz! However wouldn't it be nice to only show the volume bars you actually can use and hide theme when they are not active?

**Comment by raven2cz** [comment]
This is not bug. Your pipewire provides HDMI channel as HD-Audio Generic. Not for example HDA ATI HDMI, which is accoding to PulseAudio standard. It seems that this labeling is problem of mapping of pipewire to the pulse audio API. The name is generalized.

Why it is available and seems that do nothing? Because it is connected, in idle or suspended mode. But connected. If you want to pass sound by hdmi, it will be immediately changed status to running. But the scale bar has to be present before running, because user needs possibility to change volume before playing the sound.

I don't see the bug here. Except the generalized naming caused by mapping of pipewire to pulse audio. But it is upstream problem, not volctl. 

Wait with issue status to response from buzz. Buzz is owner this repo.

**Comment by buzz** [comment]
@FreaxMATE

I also think this is not related to volctl. You should be able to disable the output in pavucontrol or in pipewire/pulseaudio, so it's not used by your audio daemon.

**Comment by FreaxMATE** [comment]
🙈 thanks @buzz I wasn't aware that you can actually turn a device easily off either in mate-volume-control or pavucontrol.

![Screenshot at 2021-08-22 22-31-20](https://user-images.githubusercontent.com/49864414/130369227-ff1c0b20-927b-4b79-aa1c-8ff97e6c8055.png)

Sorry for opening this issue.

**Comment by buzz** [comment]
@FreaxMATE No worries, mate!
