### ISSUE TITLE
Installation error ... 

### ISSUE THREAD

**Issue by aiamuzz** [buzz/volctl#60]
Distro : Deepin Linux(Debian based)
Pavucontrol installed 

Installation error ...

```
$ sudo ./setup.py install
[sudo] password for muz: 
Verification successful
Traceback (most recent call last):
  File "./setup.py", line 5, in <module>
    from setuptools import find_packages, setup
ImportError: No module named setuptools

```

**Comment by raven2cz** [comment]
Because you is used manual way. In this case, you have to handle appropriate dependencies by yourself. 

You have two choices, use automatic way with python pip, or continue with manual way to install deps.

https://packaging.python.org/guides/installing-using-linux-tools/#debian-ubuntu
https://packaging.python.org/key_projects/#setuptools

```bash
sudo apt update
sudo apt install python3-venv python3-pip
```

**Comment by aiamuzz** [comment]
> use automatic way with python pip

@raven2cz ... I don't see any automatic way being described on the project page ?

Could you please list out the steps to install the automatic way ?
thanks.

**Comment by raven2cz** [comment]
sorry, automatic way is just for aur repo now. 
You have to use install steps by README page.
